version: '3'
services:
  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    command: "-s haha"
    ports:
      - "8545:8545"
  web:
    container_name: web
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - ganache
    links:
      - ganache:ganache
   
