version: '2'

services:
   ipfsA:
     image: ipfs/go-ipfs
     container_name: "ipfsA"
     environment:
      - IPFS_BIND_IP=127.0.0.1
      - IPFS_BOOTSTRAP_RM_ALL=true
      - GATEWAY_PORT=8080
      - API_PORT=5001
     ports:
       - 4001:4001
       - 5001:5001
       - 8080:8080
     volumes:
       - ./ipfsA:/data/ipfs/ 
   ipfsB:
     image: ipfs/go-ipfs
     container_name: "ipfsB"
     ports:
       - 6001:4001
       - 7001:5001
     volumes:
       - ./ipfsB:/data/ipfs/ 